### ISSUE TITLE
Estilos não deveriam ser tão abrangentes

### ISSUE THREAD

**Issue by guiguetz** [ramaraminha/algocracia#5]
Por uma questão de boa prática, é sempre recomendado evitar usar atribuições de estilo diretamente num elemento, como o `ul`, `a` ou `img`, especialmente num style.css que normalmente é global em todo o site.

Se a imagem vai aparecer somente uma vez nessa tela, dá um id (`<img id="logo-header" />`) e acessa esse cara no css com um

```css
#logo-header {
  width: 150px;
  height: 96px;
}
``` 

> **Importante:** IDs são únicos e não podem ser repetidos.

Caso seja um elemento que se repete na tela, usa uma class nele, como por exemplo `class="link-navigation"`, podendo customizar assim:

```css
.link-navigation {
  color: firebrick;
  background: skyblue;
  border-radius: 8px;
  padding: 8px 4px;
}
```

https://github.com/ramaraminha/algocracia/blob/072ced04beb37ebcefda2c049446fb2d4004645a/styles.css#L1-L90
